### ISSUE TITLE
No Config Settings

### ISSUE THREAD

**Issue by Uncomfortable90zaza** [ZehsTeam/Lethal-Company-KidnapperFoxSettings#1]
I've been trying to find a way to remove the fox, and this mod is not helpful. Config settings didn't appear. Tried launching the game, still no config settings.

**Comment by ZehsTeam** [comment]
@Uncomfortable90zaza 

1. Did you install the mod manually or through a mod manager?

2. Check to see if the mod is properly installed and being loaded when you run the game. You should see this log message in the console.
![image](https://github.com/user-attachments/assets/ec90f925-fb36-4295-956b-9df58c2ead37)

3. Did you check your `BepInEx > config` folder for the `com.github.zehsteam.KidnapperFoxSettings.cfg` file?

![image](https://github.com/user-attachments/assets/d1e1bba9-7633-4c3f-97eb-d1efb570a6ff)

![image](https://github.com/user-attachments/assets/bbfae4fe-068d-405e-9cff-05750528596d)

If you are using a mod manager, you can check for the config file by using their built-in config editor. Try searching `KidnapperFoxSettings`.
